import { useState, useEffect, useRef, useCallback } from 'react'
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom'
import HistoryPanel from './components/HistoryPanel.jsx'
import ResponseOutput from './components/ResponseOutput.jsx'
import ThemeToggle from './components/ThemeToggle.jsx'
import MicButton from './components/MicButton.jsx'
import './App.css'
import SettingsPanel from './components/SettingsPanel.jsx'

function Home() {
  const [queryText, setQueryText] = useState('')
  const [response, setResponse] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [isListening, setIsListening] = useState(false)
  const [speechSupported, setSpeechSupported] = useState(false)
  
  const recognitionRef = useRef(null)
  const isMountedRef = useRef(false)
  const abortControllerRef = useRef(null)
  const mockTimerRef = useRef(null)
  const latestTranscriptRef = useRef('')

  // Retrieve or generate a stable session ID so query history shows up in history panel
  const [sessionId, setSessionId] = useState(() => {
    const key = 'devwhisper_session_id'
    const existing = sessionStorage.getItem(key)
    if (existing) return existing
    const newId = 'web-' + Math.random().toString(36).substring(2, 9)
    sessionStorage.setItem(key, newId)
    return newId
  })

  // Clear conversation handler
  const handleClearChat = async () => {
    if (loading) return

    setResponse('')
    setQueryText('')
    setError(null)

    const newId = 'web-' + Math.random().toString(36).substring(2, 9)
    sessionStorage.setItem('devwhisper_session_id', newId)
    setSessionId(newId)

    try {
      const res = await fetch('/reset', {
        method: 'POST'
      })
      if (!res.ok) {
        console.error('Failed to reset conversation memory.')
      }
    } catch (err) {
      console.error('Error resetting conversation memory:', err)
    }
  }

  // Webhook Fallback Function
  const handleWebhookFallback = useCallback(async (fallbackQuery) => {
    const q = fallbackQuery !== undefined ? fallbackQuery : queryText
    const payload = {
      message: {
        type: 'tool-calls',
        sessionId: sessionId,
        toolCalls: [
          {
            id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2),
            type: 'function',
            function: {
              name: 'query_codebase',
              arguments: JSON.stringify({ query: q })
            }
          }
        ]
      }
    }

    const res = await fetch('/webhook', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    })

    if (!res.ok) {
      throw new Error(`Server returned HTTP ${res.status}`)
    }

    const data = await res.json()
    if (data.status === 'error') {
      throw new Error(data.message || 'Error executing codebase query.')
    }

    const resultText = data.results?.[0]?.result
    if (isMountedRef.current) {
      if (resultText) {
        setResponse(resultText)
      } else {
        setResponse('No response was generated by the codebase assistant.')
      }
    }
  }, [queryText, sessionId])

  // Submit Query Function
  const submitQueryText = useCallback(async (textToSubmit) => {
    const currentQuery = textToSubmit || queryText
    if (!currentQuery.trim() || loading) return

    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
    }
    abortControllerRef.current = new AbortController()
    const signal = abortControllerRef.current.signal

    setLoading(true)
    setError(null)
    setResponse('')

    try {
      const responseStream = await fetch('/stream', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ query: currentQuery, sessionId: sessionId }),
        signal
      })

      if (!responseStream.ok) {
        if (responseStream.status === 404) {
          await handleWebhookFallback(currentQuery)
          return
        }
        throw new Error(`Streaming failed: HTTP ${responseStream.status}`)
      }

      if (!responseStream.body) {
        throw new Error('Readable stream not supported or empty body returned.')
      }

      const reader = responseStream.body.getReader()
      const decoder = new TextDecoder()
      let done = false
      let accumulated = ''

      while (!done) {
        const { value, done: readerDone } = await reader.read()
        done = readerDone
        if (value) {
          const chunk = decoder.decode(value, { stream: !done })
          accumulated += chunk
          if (isMountedRef.current) {
            setResponse(accumulated)
          }
        }
      }
    } catch (err) {
      if (err.name === 'AbortError') {
        return
      }
      console.warn('Streaming failed or not available, falling back to static webhook:', err)
      if (isMountedRef.current) {
        try {
          await handleWebhookFallback(currentQuery)
        } catch (fallbackErr) {
          if (isMountedRef.current) {
            setError(fallbackErr.message || 'Failed to reach the DevWhisper backend.')
          }
        }
      }
    } finally {
      if (isMountedRef.current) {
        setLoading(false)
      }
    }
  }, [queryText, loading, sessionId, handleWebhookFallback])

  // Form Submit Handler
  const handleSubmit = (e) => {
    if (e) e.preventDefault()
    if (isListening) return
    submitQueryText(queryText)
  }

  // Initialize Speech Recognition API with complete E2E Voice Flow
  useEffect(() => {
    isMountedRef.current = true
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    if (SpeechRecognition) {
      setSpeechSupported(true)
      const rec = new SpeechRecognition()
      rec.continuous = false // Auto-stop when user stops speaking
      rec.interimResults = true
      rec.lang = 'en-US'

      rec.onstart = () => {
        if (isMountedRef.current) {
          setIsListening(true)
          setError(null)
        }
      }

      rec.onresult = (event) => {
        let transcript = ''
        for (let i = 0; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript
        }
        if (isMountedRef.current) {
          setQueryText(transcript)
          latestTranscriptRef.current = transcript
        }
      }

      rec.onerror = (err) => {
        console.error('Speech Recognition Error:', err)
        if (isMountedRef.current) {
          setIsListening(false)
          if (err.error === 'not-allowed' || err.error === 'service-not-allowed') {
            setError('Microphone permission denied. Please allow mic access in your browser.')
          } else if (err.error === 'no-speech') {
            setError('No speech was detected. Please try pressing the mic and speaking again.')
          } else if (err.error === 'network') {
            setError('Speech recognition failed due to a network error.')
          } else {
            setError(`Speech recognition error: ${err.error}`)
          }
        }
      }

      rec.onend = () => {
        if (isMountedRef.current) {
          setIsListening(false)
          const finalQuery = latestTranscriptRef.current.trim()
          if (finalQuery) {
            submitQueryText(finalQuery)
          }
        }
      }

      recognitionRef.current = rec
    }

    return () => {
      isMountedRef.current = false

      if (recognitionRef.current) {
        recognitionRef.current.abort()
      }

      if (mockTimerRef.current) {
        clearTimeout(mockTimerRef.current)
        mockTimerRef.current = null
      }

      if (abortControllerRef.current) {
        abortControllerRef.current.abort()
      }
    }
  }, [submitQueryText])

  const handleMicClick = () => {
    if (speechSupported && recognitionRef.current) {
      if (isListening) {
        recognitionRef.current.stop()
      } else {
        setQueryText('')
        latestTranscriptRef.current = ''
        setError(null)
        try {
          recognitionRef.current.start()
        } catch (err) {
          console.error('Failed to start speech recognition:', err)
          setError('Failed to activate microphone. Please try again.')
        }
      }
    } else {
      // Mock Fallback for browsers/environments without SpeechRecognition
      if (isListening) {
        setIsListening(false)
        if (mockTimerRef.current) {
          clearTimeout(mockTimerRef.current)
          mockTimerRef.current = null
        }
      } else {
        setIsListening(true)
        setQueryText('Listening...')
        setError(null)
        if (mockTimerRef.current) {
          clearTimeout(mockTimerRef.current)
        }
        mockTimerRef.current = setTimeout(() => {
          if (isMountedRef.current) {
            setIsListening(false)
            const sampleQuery = 'In main.py, what functions are found?'
            setQueryText(sampleQuery)
            submitQueryText(sampleQuery)
            mockTimerRef.current = null
          }
        }, 3000)
      }
    }
  }

  return (
    <div className="landing-container">
      <header className="hero-header">
        <h1 className="logo-text">DevWhisper</h1>
        <p className="subtitle-text">Voice-native developer experience agent</p>
      </header>

      <main className="query-card">
        <form onSubmit={handleSubmit} className="query-form">
          <div className="textarea-wrapper">
            <textarea
              value={queryText}
              onChange={e => setQueryText(e.target.value)}
              placeholder={isListening ? "Listening... Speak now." : "Ask about your codebase... (e.g., In main.py, what functions are found?)"}
              disabled={loading}
              rows={3}
              className="query-input"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault()
                  handleSubmit()
                }
              }}
            />
            
            <div className="query-toolbar">
              <div className="toolbar-left">
                <MicButton 
                  isListening={isListening} 
                  onClick={handleMicClick}
                  disabled={loading}
                />
                <div className="voice-status-info">
                  <span className={`status-dot ${isListening ? 'listening' : 'ready'}`}></span>
                  <span className="status-message">
                    {isListening 
                      ? (speechSupported ? "Listening... Speak now" : "Listening (Mock)...") 
                      : "Voice assistant ready"}
                  </span>
                </div>
              </div>
              
              <div className="toolbar-right">
                <button
                  type="button"
                  onClick={handleClearChat}
                  disabled={loading || (!queryText.trim() && !response && !error)}
                  className="clear-button"
                  title="Clear conversation"
                >
                  Clear Chat
                </button>
                <button 
                  type="submit" 
                  disabled={loading || !queryText.trim() || isListening} 
                  className="submit-button"
                >
                  {loading ? 'Analyzing...' : 'Send Query'}
                </button>
              </div>
            </div>
          </div>
        </form>

        {/* Response & Error Rendering */}
        <ResponseOutput response={response} loading={loading} error={error} />
      </main>

      <footer className="landing-footer">
        <p className="session-info">
          Active Session ID: <code>{sessionId}</code>
        </p>
        <Link to="/history" className="history-link">
          📋 View Full Session History &rarr;
        </Link>
      </footer>
    </div>
  )
}

function App() {
  return (
    <BrowserRouter>
      <div className="app">
        <SettingsPanel />

        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/history" element={<HistoryPanel />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App
