import { useState, useEffect, useRef } from 'react'
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom'
import HistoryPanel from './components/HistoryPanel.jsx'
import ResponseOutput from './components/ResponseOutput.jsx'
import ThemeToggle from './components/ThemeToggle.jsx'
import MicButton from './components/MicButton.jsx'
import './App.css'

function Home() {
  const [queryText, setQueryText] = useState('')
  const [response, setResponse] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [isListening, setIsListening] = useState(false)
  const [speechSupported, setSpeechSupported] = useState(false)
  const recognitionRef = useRef(null)

  // Retrieve or generate a stable session ID so that query history shows up in the history panel
  const [sessionId] = useState(() => {
    const key = 'devwhisper_session_id'
    const existing = sessionStorage.getItem(key)
    if (existing) return existing
    const newId = 'web-' + Math.random().toString(36).substring(2, 9)
    sessionStorage.setItem(key, newId)
    return newId
  })

  // Initialize Speech Recognition API
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    if (SpeechRecognition) {
      setSpeechSupported(true)
      const rec = new SpeechRecognition()
      rec.continuous = true
      rec.interimResults = true
      rec.lang = 'en-US'

      rec.onstart = () => {
        setIsListening(true)
      }

      rec.onresult = (event) => {
        let transcript = ''
        for (let i = 0; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript
        }
        setQueryText(transcript)
      }

      rec.onerror = (err) => {
        console.error('Speech Recognition Error:', err)
        setIsListening(false)
      }

      rec.onend = () => {
        setIsListening(false)
      }

      recognitionRef.current = rec
    }

    return () => {
      if (recognitionRef.current) {
        recognitionRef.current.abort()
      }
    }
  }, [])

  const handleMicClick = () => {
    if (speechSupported && recognitionRef.current) {
      if (isListening) {
        recognitionRef.current.stop()
      } else {
        setQueryText('')
        try {
          recognitionRef.current.start()
        } catch (err) {
          console.error('Failed to start speech recognition:', err)
        }
      }
    } else {
      // Mock Fallback for browsers/environments without SpeechRecognition
      if (isListening) {
        setIsListening(false)
      } else {
        setIsListening(true)
        setQueryText('Listening...')
        setTimeout(() => {
          setIsListening(prev => {
            if (prev) {
              setQueryText('In main.py, what functions are found?')
              return false
            }
            return prev
          })
        }, 3000)
      }
    }
  }

  const handleWebhookFallback = async () => {
    const payload = {
      message: {
        type: 'tool-calls',
        sessionId: sessionId,
        toolCalls: [
          {
            id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2),
            type: 'function',
            function: {
              name: 'query_codebase',
              arguments: JSON.stringify({ query: queryText })
            }
          }
        ]
      }
    }

    const res = await fetch('/webhook', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    })

    if (!res.ok) {
      throw new Error(`Server returned HTTP ${res.status}`)
    }

    const data = await res.json()
    if (data.status === 'error') {
      throw new Error(data.message || 'Error executing codebase query.')
    }

    const resultText = data.results?.[0]?.result
    if (resultText) {
      setResponse(resultText)
      setQueryText('')
    } else {
      setResponse('No response was generated by the codebase assistant.')
    }
  }

  const handleSubmit = async (e) => {
    if (e) e.preventDefault()
    if (!queryText.trim() || loading || isListening) return

    setLoading(true)
    setError(null)
    setResponse('')

    try {
      const responseStream = await fetch('/stream', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ query: queryText, sessionId: sessionId })
      })

      if (!responseStream.ok) {
        if (responseStream.status === 404) {
          await handleWebhookFallback()
          return
        }
        throw new Error(`Streaming failed: HTTP ${responseStream.status}`)
      }

      if (!responseStream.body) {
        throw new Error('Readable stream not supported or empty body returned.')
      }

      const reader = responseStream.body.getReader()
      const decoder = new TextDecoder()
      let done = false
      let accumulated = ''

      while (!done) {
        const { value, done: readerDone } = await reader.read()
        done = readerDone
        if (value) {
          const chunk = decoder.decode(value, { stream: !done })
          accumulated += chunk
          setResponse(accumulated)
        }
      }

      setQueryText('')
    } catch (err) {
      console.warn('Streaming failed or not available, falling back to static webhook:', err)
      try {
        await handleWebhookFallback()
      } catch (fallbackErr) {
        setError(fallbackErr.message || 'Failed to reach the DevWhisper backend.')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="landing-container">
      <header className="hero-header">
        <h1 className="logo-text">DevWhisper</h1>
        <p className="subtitle-text">Voice-native developer experience agent</p>
      </header>

      <main className="query-card">
        <form onSubmit={handleSubmit} className="query-form">
          <div className="textarea-wrapper">
            <textarea
              value={queryText}
              onChange={e => setQueryText(e.target.value)}
              placeholder={isListening ? "Listening... Speak now." : "Ask about your codebase... (e.g., In main.py, what functions are found?)"}
              disabled={loading}
              rows={3}
              className="query-input"
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault()
                  handleSubmit()
                }
              }}
            />
            
            <div className="query-toolbar">
              <div className="toolbar-left">
                <MicButton 
                  isListening={isListening} 
                  onClick={handleMicClick}
                  disabled={loading}
                />
                <div className="voice-status-info">
                  <span className={`status-dot ${isListening ? 'listening' : 'ready'}`}></span>
                  <span className="status-message">
                    {isListening 
                      ? (speechSupported ? "Listening..." : "Listening (Mock)...") 
                      : "Voice assistant ready"}
                  </span>
                </div>
              </div>
              
              <button 
                type="submit" 
                disabled={loading || !queryText.trim() || isListening} 
                className="submit-button"
              >
                {loading ? 'Analyzing...' : 'Send Query'}
              </button>
            </div>
          </div>
        </form>

        {/* Response Rendering */}
        <ResponseOutput response={response} loading={loading} error={error} />
      </main>

      <footer className="landing-footer">
        <p className="session-info">
          Active Session ID: <code>{sessionId}</code>
        </p>
        <Link to="/history" className="history-link">
          📋 View Full Session History &rarr;
        </Link>
      </footer>
    </div>
  )
}

function App() {
  return (
    <BrowserRouter>
      <div className="app">
        <ThemeToggle />

        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/history" element={<HistoryPanel />} />
        </Routes>
      </div>
    </BrowserRouter>
  );
}

export default App